import re
import pylru


def get_diff_from_commit(commit):
    # commits generated by blame don't have the full multi-line message
    # https://github.com/gitpython-developers/GitPython/issues/485
    # We read the full commit data stream as a workaround for that.
    commit_message = commit.data_stream.read()
    diff_regex = r'^Differential Revision: (https://code.uberinternal.com/D[0-9]+)$'
    match = re.search(diff_regex, commit_message, re.MULTILINE)
    if not match:
        return None
    return match.group(1)


def get_line_blames(repo, filename, linenos):
    line_blames = {}
    for blame_entry in repo.blame_incremental('HEAD', filename):
        for lineno in linenos:
            if lineno in blame_entry.linenos:
                line_blames[lineno] = blame_entry.commit
    return line_blames


def get_line_blame(repo, filename, lineno):
    for blame_entry in get_blame(repo, filename):
        if lineno in blame_entry.linenos:
            return blame_entry.commit
    raise Exception("No commit history for line")


@pylru.lrudecorator(10)
def get_blame(repo, filename):
    return list(repo.blame_incremental('HEAD', filename))
